# Generated by Django 3.0.4 on 2020-05-16 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mo_nu', models.IntegerField(max_length=10)),
                ('email', models.CharField(max_length=30)),
                ('password', models.IntegerField(max_length=15)),
                ('city', models.CharField(max_length=25)),
                ('about', models.CharField(max_length=100)),
                ('dp', models.ImageField(default='Media/default.png', upload_to='user_dp')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
