# Generated by Django 3.0.4 on 2020-05-16 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_dp', models.ImageField(default='Media/home.png', upload_to='Property_dp')),
                ('area', models.IntegerField(max_length=5)),
                ('room', models.IntegerField(max_length=2)),
                ('city', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=25)),
                ('about_property', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('property_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='property_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_img', models.ImageField(upload_to='property_img')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property.property')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fav', models.BooleanField(default=False)),
                ('is_book', models.BooleanField(default=False)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property.property')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
